inherit_from: .rubocop_todo.yml

require: rubocop-rails
AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - 'bin/**/*'

Metrics/BlockLength:
  Max: 30

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false
